sl-sh-dev/sl-sh

contrib/gpwclark/bash-completions.lisp
once args includes "" for empty character in args it will also fix the issue for tab completion with stuff like `git add READM<tab>`
=> simplify bash completion script

docs/docstruct.lisp, lisp/slsh-std.lisp, src/builtins_math.rs, src/symbols.rs
These are only in the root namespace now (not both math and root).
They avoid some unneeded allocations for better performance as well as
better int/float handling.
This avoids both the allocations that we talked about collapsing to one.  It does improve performance, sadly not as much as I hoped but measurable, which is important for something used this often.
These were not the best examples for you new math, they go back to some of the first code in sl-sh...
=> Some tweaks to the core (+, -, /, *, %) functions.

Cargo.lock, Cargo.toml, src/analyze.rs, src/builtins_file.rs, src/builtins_io.rs, src/builtins_str.rs, src/completions.rs, src/eval.rs, src/process.rs, src/reader.rs, src/shell.rs, src/symbols.rs
patch to allow this script to work:
```
(pipe (syscall "ls" "-alh") (iterator::for l in stdin (print "line: " l)))
```
=> patch to allow using iterators with stdin

Cargo.lock, bridge_types/src/lib.rs, builtins/src/io.rs, builtins/src/types/numbers.rs, builtins/src/types/string_char.rs, compile_state/src/state.rs, slosh/Cargo.toml, slosh/src/main.rs, vm/src/value.rs
- made a test that checks the format of rust docs, or at least, the strings the get-prop function gets for the :doc-string keywork
- migrated some docs over from sl-sh
- added some EXEMPTIONS
- did a bit of work with the ErrorStrings I'm basing my errors in the conversion lib functions.
main point was to get the docstrings in rust and make sure they were formatted correctly so if you break something in rust, cargo test tells you. obviously incomplete because of the EXEMPTIONS set but it is a start. Mainly a pre-cursor to me actually eval-ing the Example: sections for the docs that do have them.
=> Test rust docs in rust

shell/src/command_data.rs, slosh/src/main.rs
Simple fix for starting slosh with -c and a string of lisp code to execute.
This is pretty straightforward.  It does require using quotes to pass it as a string otherwise the shell will interpret the parens as a subshell request.  Need to push the boundaries on the shell/lisp reader interaction...
=> Make -c work with strings of lisp code.

README.md, builtins/src/types/numbers.rs, shell/src/command_data.rs, vm/src/value.rs, vm/src/vm.rs, vm/src/vm/macros.rs
This implementation allows us to store floats with greater precision.
The existing implementation stores `slvm::Value::Float` as a wrapped `f32` and ignores the other 3 available bytes.
- `builtins/src/types/numbers.rs` primarily just has the new test cases (100 of them!)
- `vm/src/value.rs` has the actual `F56` implementation and some changes from the previous implementation using `F32Wrap`
- `vm/src/vm/macros.rs` might require some additional attention. The `get_float` macro here is now set to operate on `f64` types. But a similar `get_float` macro in `value.rs` is set to `f32`.  These implications should be explored.
=> feat: support for F56 56-bit floating point numbers

slosh/benches/all.rs, slosh/benches/bench.slosh
@StevenLove even though the first two calls to eval-pol print out numbers in a given precision:
`399.999999999585` 
even though the correct answer as input by the program and correctly passed was: `399.99999999958527`
```
λ⸨⚙ ⸩ → ./bench.slosh
slosh 0.10.0 (test-new-floats:cee5608+, debug build, macos [aarch64], Feb 28 2024, 05:16:07 UTC [rustc 1.76.0 (07dca489a 2024-02-04)])
Using default slshrc written to "~/.config/slosh/init.slosh".
Edit this file to remove this message and customize your shell
(eval-pol 100 0.5) =>
399.999999999585
passed: true
(eval-pol 1000 0.05) =>
2105.263157892448
passed: true
(eval-pol 10000 0.2) =>
24999.999999998603
passed: true
```
is the printing working properly? Proof of issue is essentially 
1.  prints
```(eval-pol 100 0.5) =>
399.999999999585```
2 but …
=> Float bencher update

builtins/trybuild/tests/borrow_checker_immut_mut_fail.rs, builtins/trybuild/tests/borrow_checker_immut_mut_fail.stderr, builtins/trybuild/tests/borrow_checker_two_mut_fail.rs, builtins/trybuild/tests/borrow_checker_two_mut_fail.stderr
because the SloshVm needs to be mutable to do allocations etc. I have run into an issue I demonstrated in the two test cases and their compile errors. Basically, I have to pull variables out of their value types into actual rust types so they can be manipulated by the target functions. Both tests are examples of behavior that might need to happen inside my macro.
Now this does mean that If I have a function that accepts 
```
#[sl_sh_fn("myfn")]
fn myfn(s1: &str, s2: &str, s3: &str) { ... }
```
I'll be fine because I can have as many immutable references to the vm as I want
```
let s1: &str = (&s1).sl_as_ref(&vm).unwrap();
let s2: &str = (&s2).sl_as_ref(&vm).unwrap();
let s3: &str = (&s3).sl_as_ref(&vm).unwrap();
myfn(s1, s2, s3); // I'm actually inlining myfn but this gets my point …
```
=> 3. added two trybuild tests and their accompanying errors that demonstrate an issue I'm having

bridge_adapters/src/lisp_adapters/collections.rs, bridge_types/src/lib.rs, builtins/src/collections.rs, builtins/src/fs_meta.rs, builtins/src/rand.rs, compiler/src/compile/destructure.rs, slosh_test/src/docs.rs, vm/src/heap.rs, vm/src/heap/vm_hashmap.rs, vm/src/value.rs, vm/src/vm.rs, vm/src/vm/call_collection.rs, vm/src/vm/exec_loop.rs, vm/src/vm/storage.rs
This is a bugfix PR, the fs-crawl tests exposed a couple of issue not related to fs-crawl...
- When using maps in lisp String and StringConst will hash to the same value for the same string.
- Fixed an issue with inc!/dec! on closed over values (they did not work).
- Tweaked the random tests so they should not fail about 1% of the time (see recent main CI failure).
=> Fix issues exposed by fs-crawl tests (map, inc!/dec! bugs).

bridge_macros/src/lib.rs, builtins/trybuild/tests/too_many_generics_fail.rs, compile_state/src/state.rs, slosh_test/src/docs.rs
Github CI runners are now using Cargo 1.78.0 which includes clippy 0.1.78 which added some new warnings which I resolve in this commit.
1. In `bridge_macros/src/lib.rs` and
2. In `slosh_test/src/docs.rs`, there were some `needless_borrow`s with the warning: this expression creates a reference which is immediately dereferenced by the compiler
3. in `builtins/trybuild/tests/too_many_generics_fail.rs` we expect an exact error message about generics. After the update it was also warning that variable `b` was unused, so I added a call to println! `b` so it is no longer unused and the error message now looks just as expected.
4. in `compile_state/src/state.rs` a new warning about assigning clones should be ignored.
> The `clone_from` method in Rust replaces the current value in-place with the …
=> Satisfy clippy 0.1.78

builtins/src/collections.rs, compile_state/src/state.rs, compiler/src/load_eval.rs, lisp/core.slosh, lisp/iterator.slosh, vm/src/heap.rs, vm/src/vm/call.rs, vm/src/vm/exec_loop.rs, vm/src/vm/storage.rs
This also fixes a GC bug, asserts could double eval forms on failure and assert-error was broken.  Fixed some tests that only passed because assert-error was broken.
This is just the iterator start, needs a lot of stuff (filter, reduce, etc) but with bugfixes want to go ahead and get it in expand later.
The new iterators are a LOT simpler than in slush...
=> Iterator foundation

init.slosh
init.slosh has us printing the result of this statement `(" (str-trim $sh(cat ~/.local/share/sl-sh/history | grep -v "<ctx>" | wc -l)) ")")`
but it gives me `Reader error: Unquote outside of a back-quote` so we should remove or fix
=> Remove slosh history line count from default init.slosh

README.md, init.slosh
Addressing issue #121 makes these changes to the readme
- recommending that users performing a new installation should migrate their existing rc files' contents into their init.slosh file
- changing the `install` command from using the `-D` flag which is not supported on mac to doing the more universal `mkdir -p`
- adding /usr/bin to the PATH
=> Update readme installation instructions for mac [skip ci]

builtins/src/collections.rs, builtins/src/lib.rs, builtins/src/print.rs, compile_state/src/state.rs, compiler/src/compile.rs, compiler/src/compile/compile_call.rs, compiler/src/compile/compile_store.rs, compiler/src/load_eval.rs, compiler/src/reader.rs, doc/.gitignore, doc/src/SUMMARY.md, doc/src/namespaces.md, init.slosh, lisp/core.slosh, lisp/iterator.slosh, lisp/sh-color.slosh, lisp/test.slosh, slosh/bench_utils/benches/float-bench.slosh, slosh/bench_utils/benches/vec-search-bench.slosh, slosh/tests/equality.slosh, slosh_lib/src/lib.rs, slosh_lib/src/liner_rules.rs, slosh_test/run-tests.slosh
See docs for load, run-script, ns, with-ns, import.
Add namespace support.  It is really just bookkeeping in the compiler but there were some interesting load issues.  The load special form now compiles the file at compile time (run-script works 100% at runtime like old load).
Also added a comp-time special form that runs arbitrary code at compile time (similar to macros).
Macros are installed fully at compile time now (using cost-time), this fixes a chicken egg macros issue when using them as you define them.
=> Initial namespace support.

bridge_macros/src/lib.rs, slosh_lib/src/lib.rs, vm/Cargo.toml, vm/src/fxhasher.rs, vm/src/vm/macros.rs
apply clippy lint `for_loops_over_fallibles`
apply clippy lint `doc_lazy_continuation`
apply clippy lint `needless_borrows_for_generic_args `
ignore clippy lint `macro_metavars_in_unsafe`
fixed clippy lint `unexpected_cfgs` by removing code that would support a no_std build
remove unused feature options from vm
=> Fix Clippy issues from upgrading to Clippy 0.1.80

bridge_adapters/src/lisp_adapters.rs
We just have one violation of Clippy's lint [needless_maybe_sized](https://rust-lang.github.io/rust-clippy/master/index.html#/needless_maybe_sized) for 
```rust
// line 137 of lisp_adapters.rs
T: SlFromRef<'a, Value> + 'a + ?Sized,
```
Since the type `T` must satisfy the `SlFromRef<'a, Value>` bound which is itself defined to be `Sized`
```rust
// line 167 of lisp_adapters.rs
pub trait SlFromRef<'a, T: BridgedType>
where
Self: Sized,
{
//...
}
```
=> chore: appease clippy 0.1.81

doc/mk-site.sh
When we generate slosh docs, this code modifies a generated .js file and allows us to search for strings like `%` or `$`
=> docs: allow searching symbols in mdbook slosh docs

Justfile, README.md, scripts/check-clippy-version.sh
[Just](https://github.com/casey/just) is a popular command runner to replace `make`. I have struggled to remember and to type the exact wording of various tests so this allows me to type `just test` and cover all of my bases.  
Also note the script that checks the version of `cargo clippy` in the CI and compares it to your local `cargo clippy` version to remind you to update if necessary
=> Added justfile

lisp/core.slosh
Problem 1: argument order was incorrect for `str-starts-with` so the result was always `false`.
Problem 2: some quoting and unquoting needed to be rearranged in order to get `has-usage` to actually be evaluated properly
Without this fix, you can issue a command like `(doc 'rem)` and see that the usage string is printed twice because the `doc` macro can't find an existing usage string and decides to try to add the usage string, doubling it.
=> fix: docs macro no longer double-printing usage string

bridge_macros/src/lib.rs, builtins/src/collections.rs, builtins/src/lib.rs, builtins/src/print.rs, compile_state/src/state.rs, doc/book.toml, doc/mdbook-slosh-eval/Cargo.lock, doc/mdbook-slosh-eval/Cargo.toml, doc/mdbook-slosh-eval/build.rs, doc/mdbook-slosh-eval/src/main.rs, doc/mk-site.sh, doc/src/SUMMARY.md, doc/src/overview.md, slosh/src/main.rs, slosh_lib/src/lib.rs, slosh_test/src/main.rs, slosh_test_lib/src/docs.rs, slosh_test_lib/src/lib.rs, vm/src/value.rs
new builtin functions to swap out builtin functions with the builtin noop function (returns Nil) and back. Used by the mdbook slosh eval crate to disallow writing to stdout by temporarily making pr/prn/dasm return Nil (noop).
=> allow any user file to be safely loaded within context of user doc generation

.github/workflows/pr_benchmarks.yml, .github/workflows/rust.yml, Cargo.lock, Cargo.toml, builtins/src/fs_meta.rs, builtins/src/io.rs, builtins/src/rand.rs, compile_state/src/state.rs, doc/mdbook-slosh-eval/Cargo.lock, shell/src/builtins.rs, shell/src/parse.rs, slosh/bench_utils/benches/bench.slosh, slosh/bench_utils/benches/vec-search-bench.slosh, slosh_lib/src/shell_builtins.rs, slosh_test_lib/src/docs.rs, slosh_test_lib/src/docs/legacy.rs
- doc:
show symbols that do not have documentation on the forms page so they are more discoverable.
- bencher:
- add thresholds so we can be notified via gh actions if a metric is lagging
- std-lib:
- fix
some old scripts
- add
get-env
set-env
unset-env
fs-fullpath
=> PR #1: Std lib/env

bridge_adapters/src/lib.rs, bridge_adapters/src/lisp_adapters.rs, bridge_adapters/src/lisp_adapters/collections.rs, bridge_adapters/src/lisp_adapters/numbers.rs, bridge_adapters/src/lisp_adapters/primitives.rs, bridge_adapters/src/lisp_adapters/text.rs, bridge_macros/src/lib.rs, bridge_types/src/lib.rs, builtins/src/lib.rs, builtins/trybuild/tests/enforce_return_fail.stderr, slosh_test_lib/src/docs.rs
Create another error type  to hold error string, convert it to VmError and add fn_name so it's less confusing which errors are failing. BridgeResult get's wrapped by VmError inside the macro call, and adds the context of the calling function's name. This allows the error to report 
`"ERROR: [conversion]: ->int: mismatched type input, expected value of type Int, got Vector."`
instead of 
`"ERROR: [conversion]: mismatched type input, expected value of type Int, got Vector."`
this has been something i've been meaning to do for awhile.
There's still a lot to do though. I'm wondering if we can't do something similar to what Rust does with miette?
=> new PR #1: BridgeError to add fn_name context to errors
